adding new action and trigger
moddio/taro pull request #216
Opened 2022-03-20 09:41 UTC by KL0maboi

added `addButtonGuiForPlayer` action and `when player clicks button` trigger

2022-03-20 09:43 UTC, KL0maboi commented
![image](https://user-images.githubusercontent.com/85732105/159156723-5630a565-7737-4221-9b78-61956fd93d27.png)

2022-03-21 15:04 UTC, m0dE requested changes

2022-03-21 15:04 UTC, m0dE commented on server/ServerNetworkEvents.js
> +			ige.trigger.fire("playerClickButton", {
rename as playerClicksCustomButton

2022-03-21 15:04 UTC, m0dE commented on src/gameClasses/ClientNetworkEvents.js
> +			case 'addButton':
rename as addCustomButton

2022-03-21 15:04 UTC, m0dE commented on src/gameClasses/components/script/ActionComponent.js
> +					case 'addButtonGuiForPlayer':
addCustomButtonForPlayer

2022-03-21 15:04 UTC, m0dE commented on src/gameClasses/components/ui/PlayerUiComponent.js
> +	addButton: function (data) {
addCustomButton

2022-03-21 15:05 UTC, m0dE commented
this is a very interesting PR. thanks!

2022-04-01 10:13 UTC, KL0maboi commented
i've added another 7 actions to customize buttons and you can test them with the json of a game i made i've attached it below
[game.txt](https://github.com/moddio/taro/files/8396764/game.txt)

2025-12-17 07:10 UTC, closed without merging