Phaser renderer remove pixi chat
moddio/taro pull request #393
Opened 2022-07-05 21:26 UTC by sloont

2022-07-05 21:27 UTC, sloont commented on ts/src/renderer/phaser/classes/PhaserChatBubble.ts
> +	protected textObject: Phaser.GameObjects.Text;
test whether this change has an effect. I don't think it did as we no longer adjust textObject `alpha`

2022-07-05 21:28 UTC, sloont commented on ts/src/renderer/phaser/classes/PhaserChatBubble.ts
> +	fadeOut(): void {
test whether these can be private again.

2022-07-05 21:29 UTC, sloont commented on ts/src/renderer/phaser/classes/PhaserChatBubble.ts
> +		this.add(bubble);
can remove cause we never remove the bubble. this was part of the issue with alpha stacking/faded text

2022-07-05 21:29 UTC, sloont commented on ts/src/renderer/phaser/scenes/GameScene.ts
> +		canvas.style.opacity = '1';
revert after tests and before merge to `phaser-renderer`

2022-07-06 11:16 UTC, sloont commented on ts/src/renderer/phaser/classes/PhaserChatBubble.ts
> +		this.add(bubble);
rather: move to constructor

2022-07-07 16:07 UTC, pavle-goloskokovic requested changes

2022-07-08 10:16 UTC, pavle-goloskokovic approved these changes

2022-07-08 10:17 UTC, merged